name: lab5
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/banner.jpg
    - assets/faculty/NM.jpg
    - assets/faculty/Dhananjay.jpeg
    - assets/faculty/SS.png
    - assets/faculty/HK.png
    - assets/events/event1.png
    - assets/events/event2.png
    - assets/events/event3.png
